# Include make.sys
include make.sys

# Export LDFLAGS
export LDFLAGS

TIMER:=$(findstring DNOTIMER,,$(FCFLAGS))
ifneq ($(TIMER),DNOTIMER)
TIMER:=$(findstring DTIMER,,$(FCFLAGS))
ifneq ($(TIMER),DTIMER)
FCFLAGS+=-DTIMER
endif
endif

F90_SERIAL?=$(F90)
	
ROOT_DIR:=$(PWD)
BUILD_DIR:=$(ROOT_DIR)/build
SRC_DIR=$(ROOT_DIR)/Src
LIB_DIR:=$(BUILD_DIR)/lib
VPATH:=$(ROOT_DIR):$(SRC_DIR)
BIN_DIR:=$(ROOT_DIR)/bin

VERSION:=$(word 2,$(shell cat version.info))-rev$(word 4,$(shell cat version.info))
ODATE:=$(subst -, ,$(word 8,$(shell cat version.info)))
YEAR:=$(word 1,$(ODATE))
MONTH:=$(word 2,$(ODATE))
DAY:=$(word 3,$(ODATE))
DATE:=$(MONTH)'-'$(DAY)'-'$(YEAR)

export ROOT_DIR BUILD_DIR SRC_DIR BIN_DIR F90
export FCFLAGS LIBS LIB_DIR VPATH ARFLAGS
export VERSION DATE INCFLAGS F90_SERIAL

default: grabnes

all: grabnes

grabnes : | $(BUILD_DIR) $(BIN_DIR)

grabnes: flags version.info
	@echo
	@echo ">> GraBNES compilation <<"
	@echo "Version: "$(VERSION)
	@echo "Updated: "$(DATE)
	@echo
	@cp -f $(SRC_DIR)/Makefile $(BUILD_DIR)
	@(cd $(BUILD_DIR) ; $(MAKE) grabnes)
	
$(BUILD_DIR):
	mkdir $(BUILD_DIR)
$(BIN_DIR):
	mkdir $(BIN_DIR)
	
.PHONY: clean flags
clean:
	@if [ -d $(BUILD_DIR) ] ; then \
	cd $(BUILD_DIR) ; $(MAKE) clean ; \
	else \
	echo 'Nothing to clean in BUILD_DIR' ; \
	fi
	@if [ -d $(LIB_DIR) ]; then \
	cd $(LIB_DIR) ; $(RM) *.a ; \
	fi 
	@if [ -d $(BIN_DIR) ]; then \
	cd $(BIN_DIR) ; $(RM) * ; \
	else \
	echo 'Nothing to clean in BIN_DIR' ; \
	fi 

version.info: .version
	@echo ">> Generating version file <<"; \
	cp .version version.info ; \
	exec 3<version.info ; \
	exec 4> .version ; \
	read line <&3 ; \
	echo "$$line" >&4 ; \
	echo "\$$Revision\$$" >&4 ; \
	echo "updated" >&4 ; \
	echo "\$$Date\$$" >&4 ; \
	echo $$(date) >&4 ; \
	touch version.info
	
